CREATE TABLE IF NOT EXISTS `symphony_article_draft` (
  `oId` VARCHAR(19) NOT NULL,
  `articleDraftUserId` VARCHAR(19) NOT NULL,
  `articleDraftTitle` VARCHAR(255) NOT NULL,
  `articleDraftSummary` VARCHAR(160) NOT NULL,
  `articleDraftContent` MEDIUMTEXT NOT NULL,
  `articleDraftThoughtContent` MEDIUMTEXT NOT NULL,
  `articleDraftTags` VARCHAR(255) NOT NULL,
  `articleDraftType` INT NOT NULL DEFAULT 0,
  `articleDraftColumnId` VARCHAR(19) NOT NULL DEFAULT '',
  `articleDraftColumnTitle` VARCHAR(64) NOT NULL DEFAULT '',
  `articleDraftChapterNo` VARCHAR(32) NOT NULL DEFAULT '',
  `articleDraftRewardContent` MEDIUMTEXT NOT NULL,
  `articleDraftRewardPoint` INT NOT NULL DEFAULT 0,
  `articleDraftQnAOfferPoint` INT NOT NULL DEFAULT 0,
  `articleDraftCommentable` CHAR(1) NOT NULL,
  `articleDraftAnonymous` CHAR(1) NOT NULL,
  `articleDraftNotifyFollowers` CHAR(1) NOT NULL,
  `articleDraftShowInList` INT NOT NULL DEFAULT 1,
  `articleDraftStatement` INT NOT NULL DEFAULT 0,
  `articleDraftCreatedTime` BIGINT NOT NULL,
  `articleDraftUpdatedTime` BIGINT NOT NULL,
  PRIMARY KEY (`oId`),
  KEY `idx_article_draft_user_updated` (`articleDraftUserId`, `articleDraftUpdatedTime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
